services:
  fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: prod_fast_api
    container_name: prod_user_profile_audit_fast_api
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - prod-db
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload

  prod-db:
    image: postgres:17-alpine
    container_name: prod_user_profile_audit_db
    ports:
      - "5444:5432"
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  pytest-fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pytest_fast_api_service
    volumes:
      - .:/app
    depends_on:
      - prod-db
      - test-db
    env_file:
      - .env
    command: pytest --disable-warnings --maxfail=1
#    stdin_open: true
#    tty: true

  test-db:
    image: postgres:17-alpine
    container_name: test_user_profile_audit_db
    ports:
      - "5445:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_user_profile_audit_db
      POSTGRES_USER: test_user_profile_user
      POSTGRES_PASSWORD: test_password

volumes:
  prod_postgres_data:
  test_postgres_data: